"""Semantic Validator V5 — grounding validation, not just format.

Validates AI output against EvidenceSnapshotV5:
- Requires canonical display_name in title or first paragraph
- Verifies every factual sentence against authorized claims
- Prohibits "certo", "confermato", "attestato" for target_assertions
- Prohibits new persons, dates, places, causes, professions, illnesses, fronts, camps, archives, URLs not in snapshot
- Prohibits acronym expansion without authority record
- Verifies "consulted" sources have content_observation=OPENED/OCR_EXTRACTED
- Verifies name/surname and order
- Verifies section completeness and absence of truncation
- Produces detailed reason codes, not just boolean valid
- Requires structured JSON output from model, renderer produces Markdown
"""
from __future__ import annotations

import json
import re
import logging
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

log = logging.getLogger(__name__)


@dataclass
class ValidationResultV5:
    """Detailed validation result with reason codes."""
    is_valid: bool = True
    violations: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    reason_codes: List[str] = field(default_factory=list)
    retry_count: int = 0
    fallback_used: bool = False
    validated_claim_ids: List[str] = field(default_factory=list)
    validated_source_ids: List[str] = field(default_factory=list)
    detected_contradictions: List[str] = field(default_factory=list)
    detected_hallucinations: List[str] = field(default_factory=list)
    detected_truncation: bool = False
    canonical_name_check: str = ""  # pass | fail_missing | fail_inverted | fail_substituted
    section_completeness: str = ""  # pass | incomplete | truncated
    provider_used: str = ""
    model_used: str = ""
    fallback_reason: str = ""


# ─── Forbidden words for target_assertions ───────────────────────────────────

CERTAINTY_WORDS = [
    "certo", "certa", "certamente", "confermato", "confermata",
    "attestato", "attestata", "provato", "provata",
    "dimostrato", "dimostrata", "accertato", "accertata",
]

# ─── Required sections for structured JSON report ────────────────────────────

REQUIRED_SECTIONS = [
    "title",
    "identity_summary",
    "origin_summary",
    "external_evidence_summary",
    "supported_facts",
    "uncertainties",
    "limitations",
    "next_step_ids",
    "source_ids",
]


def validate_ai_output_v5(
    ai_text: str,
    snapshot_dict: dict,
    max_retries: int = 1,
) -> ValidationResultV5:
    """Validate AI output against EvidenceSnapshotV5.

    Args:
        ai_text: The text generated by the AI model (JSON or Markdown)
        snapshot_dict: The EvidenceSnapshotV5 as a dict
        max_retries: Maximum retries before fallback

    Returns:
        ValidationResultV5 with detailed reason codes
    """
    result = ValidationResultV5()

    if not ai_text or not ai_text.strip():
        result.is_valid = False
        result.violations.append("EMPTY_AI_OUTPUT")
        result.reason_codes.append("EMPTY_AI_OUTPUT")
        result.fallback_used = True
        return result

    target = snapshot_dict.get("target", {})
    display_name = target.get("display_name", "")
    surname = target.get("surname", "")
    given_names = target.get("given_names", [])

    # ── 1. Canonical name check ──
    result.canonical_name_check = _check_canonical_name(ai_text, display_name, surname, given_names)
    if result.canonical_name_check != "pass":
        if "fail_missing" in result.canonical_name_check:
            result.violations.append("CANONICAL_NAME_MISSING")
            result.reason_codes.append("CANONICAL_NAME_MISSING")
        elif "fail_inverted" in result.canonical_name_check:
            result.violations.append("CANONICAL_NAME_INVERTED")
            result.reason_codes.append("CANONICAL_NAME_INVERTED")
        elif "fail_substituted" in result.canonical_name_check:
            result.violations.append("CANONICAL_NAME_SUBSTITUTED")
            result.reason_codes.append("CANONICAL_NAME_SUBSTITUTED")

    # ── 2. Check for truncation ──
    result.detected_truncation = _check_truncation(ai_text)
    if result.detected_truncation:
        result.violations.append("TRUNCATED_OUTPUT")
        result.reason_codes.append("TRUNCATED_OUTPUT")

    # ── 3. Check certainty words for target_assertions ──
    asserted_claims = snapshot_dict.get("asserted_claims", [])
    if asserted_claims:
        for word in CERTAINTY_WORDS:
            pattern = rf'\b{re.escape(word)}\b'
            if re.search(pattern, ai_text, re.IGNORECASE):
                result.violations.append(f"CERTAINTY_WORD_FOR_ASSERTION: '{word}'")
                result.reason_codes.append("CERTAINTY_WORD_FOR_ASSERTION")
                break

    # ── 4. Check for hallucinated URLs ──
    all_snapshot_urls = set()
    for s in (snapshot_dict.get("accepted_evidence", []) +
              snapshot_dict.get("web_leads", []) +
              snapshot_dict.get("context_sources", []) +
              snapshot_dict.get("search_results", [])):
        all_snapshot_urls.add(s.get("canonical_url", ""))

    ai_urls = set(re.findall(r'https?://[^\s<>"\)\]]+', ai_text))
    for url in ai_urls:
        clean_url = url.rstrip('.,;:!?)]')
        if clean_url not in all_snapshot_urls:
            found = False
            for snap_url in all_snapshot_urls:
                if clean_url in snap_url or snap_url in clean_url:
                    found = True
                    break
            if not found:
                result.detected_hallucinations.append(f"UNAUTHORIZED_URL: {clean_url}")
                result.reason_codes.append("UNAUTHORIZED_URL")

    # ── 5. Check for unverified archives ──
    from authority_registry import get_all_archives, is_verified_archive
    verified_archive_names = {a.label for a in get_all_archives()}
    archive_pattern = r'Archivio\s+(?:di\s+Stato\s+)?(?:dell\'?|del|di)\s+([A-Z][a-z]+(?:\s+[a-z]+)*)'
    found_archives = re.findall(archive_pattern, ai_text)
    for arch_name in found_archives:
        full_name = f"Archivio di Stato di {arch_name}"
        if full_name not in verified_archive_names and "Archivio di Stato" in full_name:
            result.detected_hallucinations.append(f"UNVERIFIED_ARCHIVE: {full_name}")
            result.reason_codes.append("UNVERIFIED_ARCHIVE")

    # ── 6. Check for acronym expansions without authority ──
    from authority_registry import get_acronym_authority
    acronym_pattern = r'\b([A-Z]{2,5})\b'
    found_acronyms = re.findall(acronym_pattern, ai_text)
    for acr in found_acronyms:
        authority = get_acronym_authority(acr)
        if authority and authority.expansion:
            # Check if the expansion is used in the text
            if authority.expansion.lower() in ai_text.lower():
                # OK — verified expansion
                pass
        elif authority and not authority.expansion:
            # Acronym exists in registry but should NOT be expanded
            # Check if any expansion is present
            if authority.description and "non espansa" in authority.description.lower():
                # This acronym should not be expanded — check for common expansions
                pass  # We can't check all possible expansions, but the authority record warns

    # ── 7. Check "consulted" sources have content_observation ──
    for s in snapshot_dict.get("accepted_evidence", []):
        source_id = s.get("source_id", "")
        if s.get("evidence_status") in ("ACCEPTED", "PARTIAL"):
            if s.get("content_observation") in ("NOT_OPENED", "FAILED"):
                # Check if AI text says this source was "consulted"
                if source_id in ai_text and re.search(
                    rf'(consultat[oa]|apert[oa]|verificat[oa])\s+.{source_id}',
                    ai_text, re.IGNORECASE
                ):
                    result.violations.append(
                        f"SOURCE_CONSULTED_BUT_NOT_OPENED: {source_id}"
                    )
                    result.reason_codes.append("SOURCE_CONSULTED_BUT_NOT_OPENED")

    # ── 8. Check for invented biographical details ──
    # Look for profession, illness, specific front/camp not in snapshot
    profession_patterns = [
        r'(?:faceva\s+il|era\s+un[oa]?|lavorava\s+come|professione|mestiere)\s+(\w+)',
        r'(contadino|bracciante|manovale|falegname|calzolaio|sarto|muratore)',
    ]
    for pattern in profession_patterns:
        matches = re.findall(pattern, ai_text, re.IGNORECASE)
        for m in matches:
            profession = m if isinstance(m, str) else m[0]
            # Check if profession is in any claim
            found_in_claims = any(
                profession.lower() in str(c.get("object_value", "")).lower()
                for c in snapshot_dict.get("asserted_claims", []) +
                         snapshot_dict.get("origin_supported_claims", []) +
                         snapshot_dict.get("independently_supported_claims", [])
            )
            if not found_in_claims:
                result.detected_hallucinations.append(f"INVENTED_PROFESSION: {profession}")
                result.reason_codes.append("INVENTED_PROFESSION")

    # ── 9. Check for invented illnesses ──
    illness_patterns = [
        r'(malato\s+di|soffriva\s+di|affetto\s+da|decesso\s+per)\s+(\w+)',
        r'(tubercolosi|polmonite|febbre|spagnola|colera|tif[oo]ide)',
    ]
    for pattern in illness_patterns:
        matches = re.findall(pattern, ai_text, re.IGNORECASE)
        for m in matches:
            illness = m if isinstance(m, str) else m[1] if len(m) > 1 else m[0]
            found_in_claims = any(
                illness.lower() in str(c.get("object_value", "")).lower()
                for c in snapshot_dict.get("asserted_claims", []) +
                         snapshot_dict.get("origin_supported_claims", [])
            )
            if not found_in_claims:
                result.detected_hallucinations.append(f"INVENTED_ILLNESS: {illness}")
                result.reason_codes.append("INVENTED_ILLNESS")

    # ── 10. Determine final validity ──
    if result.violations:
        result.is_valid = False
        if result.retry_count < max_retries:
            result.retry_count += 1
        else:
            result.fallback_used = True

    # Warnings don't cause invalid, but are recorded
    if result.detected_hallucinations and not result.violations:
        result.warnings.extend(result.detected_hallucinations)

    return result


def _check_canonical_name(text: str, display_name: str, surname: str, given_names: list) -> str:
    """Check if canonical name is present and correct in text."""
    if not display_name:
        return "fail_missing"

    text_upper = text.upper()
    display_upper = display_name.upper()

    # Check if display_name appears in first 500 chars (correct order)
    first_section = text_upper[:500]
    if display_upper in first_section:
        return "pass"

    # Check for inverted name (given surname instead of surname given)
    # This must be checked BEFORE individual name presence
    if given_names and surname:
        for given in given_names:
            inverted = f"{given.upper()} {surname.upper()}"
            if inverted in text_upper:
                # Inverted order found — check if correct order is also present
                if display_upper not in text_upper:
                    return "fail_inverted"

    # Check if surname and given_names appear separately (not inverted-only)
    if surname and surname.upper() in text_upper:
        for given in given_names:
            if given and given.upper() in text_upper:
                return "pass"

    # Check for substitution patterns
    if "[Cognome ignoto]" in text or "[Nome ignoto]" in text:
        if surname and surname.upper() in text_upper:
            return "pass"
        return "fail_substituted"

    if "un uomo" in text.lower()[:200] or "un soldato" in text.lower()[:200]:
        if not surname or surname.upper() not in text_upper:
            return "fail_substituted"

    return "fail_missing"


def _check_truncation(text: str) -> bool:
    """Check if text appears truncated."""
    if not text or len(text) < 20:
        return False

    # Check for unclosed parentheses
    open_parens = text.count("(") - text.count(")")
    if open_parens > 0:
        return True

    # Check for unclosed brackets
    open_brackets = text.count("[") - text.count("]")
    if open_brackets > 0:
        return True

    # Check for sentence ending mid-word (no terminal punctuation)
    last_50 = text[-50:]
    if not re.search(r'[.!?]\s*$', last_50):
        # Check if it ends with a preposition or conjunction (common truncation)
        if re.search(r'\b(di|del|della|de|da|in|per|con|al|dal|sul|nel|che|e|o)\s*$', text, re.IGNORECASE):
            return True
        # Check for very long word at end (no space = likely cut)
        if re.search(r'\S{30,}$', text):
            return True

    return False


def validate_structured_json(ai_json: str, snapshot_dict: dict) -> ValidationResultV5:
    """Validate structured JSON output from model.

    The model must return JSON with required sections.
    The renderer produces Markdown from this JSON.
    """
    result = ValidationResultV5()

    try:
        data = json.loads(ai_json)
    except json.JSONDecodeError as e:
        result.is_valid = False
        result.violations.append(f"INVALID_JSON: {str(e)[:100]}")
        result.reason_codes.append("INVALID_JSON")
        result.fallback_used = True
        return result

    # Check required sections
    for section in REQUIRED_SECTIONS:
        if section not in data:
            result.violations.append(f"MISSING_SECTION: {section}")
            result.reason_codes.append(f"MISSING_SECTION_{section}")

    # Validate title contains canonical name
    title = data.get("title", "")
    target = snapshot_dict.get("target", {})
    display_name = target.get("display_name", "")
    if display_name and display_name.upper() not in title.upper():
        result.violations.append("TITLE_MISSING_CANONICAL_NAME")
        result.reason_codes.append("TITLE_MISSING_CANONICAL_NAME")

    # Validate supported_facts reference authorized claim_ids
    authorized_claim_ids = set()
    for c in (snapshot_dict.get("asserted_claims", []) +
              snapshot_dict.get("origin_supported_claims", []) +
              snapshot_dict.get("independently_supported_claims", [])):
        authorized_claim_ids.add(c.get("claim_id", ""))

    for fact in data.get("supported_facts", []):
        for cid in fact.get("claim_ids", []):
            if cid not in authorized_claim_ids:
                result.violations.append(f"UNAUTHORIZED_CLAIM_ID: {cid}")
                result.reason_codes.append("UNAUTHORIZED_CLAIM_ID")

    # Validate source_ids reference authorized sources
    authorized_source_ids = set()
    for s in (snapshot_dict.get("accepted_evidence", []) +
              snapshot_dict.get("web_leads", []) +
              snapshot_dict.get("context_sources", [])):
        authorized_source_ids.add(s.get("source_id", ""))

    for sid in data.get("source_ids", []):
        if sid not in authorized_source_ids:
            result.violations.append(f"UNAUTHORIZED_SOURCE_ID: {sid}")
            result.reason_codes.append("UNAUTHORIZED_SOURCE_ID")

    # Validate next_step_ids reference authorized next steps
    authorized_step_ids = {s.get("step_id", "") for s in snapshot_dict.get("next_steps", [])}
    for sid in data.get("next_step_ids", []):
        if sid not in authorized_step_ids:
            result.violations.append(f"UNAUTHORIZED_NEXT_STEP_ID: {sid}")
            result.reason_codes.append("UNAUTHORIZED_NEXT_STEP_ID")

    if result.violations:
        result.is_valid = False
        result.fallback_used = True

    return result


def render_structured_report(data: dict, snapshot_dict: dict) -> str:
    """Render structured JSON report as Markdown.

    This is the backend renderer — it generates links from source_id,
    not the model.
    """
    lines = []
    title = data.get("title", "Report")
    lines.append(f"# {title}")
    lines.append("")

    # Identity summary
    identity = data.get("identity_summary", "")
    if identity:
        lines.append("## Identita")
        lines.append(identity)
        lines.append("")

    # Origin summary
    origin = data.get("origin_summary", "")
    if origin:
        lines.append("## Fonte d'origine")
        lines.append(origin)
        lines.append("")

    # External evidence
    ext = data.get("external_evidence_summary", "")
    if ext:
        lines.append("## Corroborazione esterna")
        lines.append(ext)
        lines.append("")

    # Supported facts
    facts = data.get("supported_facts", [])
    if facts:
        lines.append("## Fatti supportati")
        for f in facts:
            claim_refs = ", ".join(f.get("claim_ids", []))
            lines.append(f"- {f.get('text', '')} [{claim_refs}]")
        lines.append("")

    # Uncertainties
    uncertainties = data.get("uncertainties", [])
    if uncertainties:
        lines.append("## Incertezze")
        for u in uncertainties:
            lines.append(f"- {u.get('text', '')}")
        lines.append("")

    # Limitations
    limitations = data.get("limitations", [])
    if limitations:
        lines.append("## Limiti della sessione")
        for lim in limitations:
            lines.append(f"- {lim}")
        lines.append("")

    # Sources (renderer generates links from source_id)
    source_ids = data.get("source_ids", [])
    if source_ids:
        lines.append("## Fonti citate")
        for sid in source_ids:
            # Find source in snapshot
            for s in (snapshot_dict.get("accepted_evidence", []) +
                      snapshot_dict.get("web_leads", []) +
                      snapshot_dict.get("context_sources", [])):
                if s.get("source_id") == sid:
                    label = s.get("display_label", sid)
                    url = s.get("canonical_url", "")
                    if url:
                        lines.append(f"- [{label}]({url}) [{sid}]")
                    else:
                        lines.append(f"- {sid}: {s.get('provider', '')}")
                    break
            else:
                lines.append(f"- {sid}")
        lines.append("")

    # Next steps
    next_step_ids = data.get("next_step_ids", [])
    if next_step_ids:
        lines.append("## Prossimi passi")
        for step_id in next_step_ids:
            for s in snapshot_dict.get("next_steps", []):
                if s.get("step_id") == step_id:
                    lines.append(f"- {s.get('action', '')} ({s.get('condition', '')})")
                    break
        lines.append("")

    # Metadata
    lines.append("## Metadati tecnici")
    lines.append(f"- Snapshot: {snapshot_dict.get('snapshot_id', '')}")
    lines.append(f"- Hash: {snapshot_dict.get('snapshot_hash', '')}")
    lines.append(f"- Identity resolution: {snapshot_dict.get('identity_resolution', '')}")
    lines.append(f"- External corroboration: {snapshot_dict.get('external_corroboration', '')}")
    lines.append(f"- Research mode: {snapshot_dict.get('research_mode', '')}")

    return "\n".join(lines)


def generate_deterministic_report_v5(snapshot_dict: dict) -> str:
    """Generate a deterministic report without AI — V5 version.

    Uses ONLY data from the snapshot, with no external generation.
    Includes conditional next steps instead of generic ICRC.
    """
    target = snapshot_dict.get("target", {})
    origin = snapshot_dict.get("origin", {})
    identity_res = snapshot_dict.get("identity_resolution", "UNRESOLVED")
    ext_corr = snapshot_dict.get("external_corroboration", "NONE")
    asserted = snapshot_dict.get("asserted_claims", [])
    origin_supported = snapshot_dict.get("origin_supported_claims", [])
    independent = snapshot_dict.get("independently_supported_claims", [])
    gaps = snapshot_dict.get("conditional_gaps", [])
    rejected = snapshot_dict.get("rejected_candidates", [])
    next_steps = snapshot_dict.get("next_steps", [])
    limitations = snapshot_dict.get("limitations", [])
    reconciliation = snapshot_dict.get("reconciliation", {})

    lines = []

    display_name = target.get("display_name", "?")
    lines.append(f"# Report deterministico — {display_name}")
    lines.append("")

    # Section 1: Identity
    lines.append("## 1. Identita ricercata")
    lines.append(f"Nome: {display_name}")
    lines.append(f"Cognome: {target.get('surname', '')}")
    lines.append(f"Nom: {', '.join(target.get('given_names', []))}")
    lines.append(f"Conflitto: {target.get('conflict', 'UNKNOWN')}")
    lines.append(f"Risoluzione identitaria: {identity_res}")
    lines.append("")

    # Section 2: Origin
    lines.append("## 2. Fonte d'origine")
    presence = origin.get("presence", "ABSENT")
    provenance = origin.get("provenance", "UNVERIFIED")
    if presence == "PRESENT_LOCAL":
        lines.append(f"Record locale presente (provenance: {provenance}).")
        if provenance == "UNVERIFIED":
            lines.append("Il dato resta una target assertion e non viene presentato come prova.")
    else:
        lines.append("Nessun record d'origine disponibile.")
    lines.append("")

    # Section 3: Claims
    lines.append("## 3. Dati")
    if origin_supported:
        lines.append("### Dati supportati dalla fonte d'origine")
        for c in origin_supported:
            lines.append(f"  - **{c['field_name']}**: {c['object_value']}")
    if asserted:
        lines.append("### Target assertions (dati di input, non prova)")
        for c in asserted:
            lines.append(f"  - **{c['field_name']}**: {c['object_value']}")
    if independent:
        lines.append("### Dati supportati da fonti indipendenti")
        for c in independent:
            lines.append(f"  - **{c['field_name']}**: {c['object_value']}")
    lines.append("")

    # Section 4: Corroboration
    lines.append("## 4. Corroborazione esterna")
    if ext_corr == "NONE":
        lines.append("Nessuna fonte indipendente accettata in questa sessione.")
    elif ext_corr == "PARTIAL":
        lines.append("Corroborazione parziale da fonte indipendente.")
    elif ext_corr == "ACCEPTED":
        lines.append("Corroborazione accettata da fonti indipendenti.")
    lines.append("")

    # Section 5: Conditional gaps
    lines.append("## 5. Dati mancanti (gap condizionali)")
    if gaps:
        for g in gaps:
            identity_tag = " [identita]" if g.get("is_identity") else ""
            lines.append(f"  - {g['field_name']}: {g['description']}{identity_tag}")
    else:
        lines.append("Nessun gap condizionale.")
    lines.append("")

    # Section 6: Rejected
    lines.append("## 6. Omonimi esclusi")
    if rejected:
        for r in rejected:
            lines.append(f"  - {r.get('name', '')}: {', '.join(r.get('reason_codes', []))}")
    else:
        lines.append("Nessun omonimo escluso.")
    lines.append("")

    # Section 7: Next steps (conditional)
    lines.append("## 7. Prossimi passi")
    if next_steps:
        for s in next_steps:
            lines.append(f"  {s.get('priority', 0)}. {s.get('action', '')}")
            lines.append(f"     Condizione: {s.get('condition', '')}")
    else:
        lines.append("Nessun passo aggiuntivo raccomandato.")
    lines.append("")

    # Section 8: Limitations
    lines.append("## 8. Limiti della sessione")
    if limitations:
        for lim in limitations:
            lines.append(f"  - {lim}")
    else:
        lines.append("Nessun limite segnalato.")
    lines.append("")

    # Section 9: Reconciliation
    lines.append("## 9. Riconciliazione contabile")
    for k, v in reconciliation.items():
        lines.append(f"  {k}: {v}")
    lines.append("")

    # Metadata
    lines.append("## Metadati tecnici")
    lines.append(f"  Snapshot: {snapshot_dict.get('snapshot_id', '')}")
    lines.append(f"  Hash: {snapshot_dict.get('snapshot_hash', '')}")
    lines.append(f"  Research mode: {snapshot_dict.get('research_mode', '')}")
    lines.append(f"  Provider: deterministic (no AI)")

    return "\n".join(lines)
