"""Post-Generation Validator V4.

Validates AI output after Mistral/local generation:
- Schema validation (JSON/Pydantic)
- Grounding validation (every claim_id and source_id belongs to snapshot)
- Contradiction detection (AI cannot deny verified origin record)
- Hallucination detection (no new names, dates, archives, URLs not in snapshot)
- Controlled retry (max 1 retry, then deterministic fallback)

finish_reason=stop is only a transport check, not a content validation.
"""
from __future__ import annotations

import re
import json
import logging
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

log = logging.getLogger(__name__)


@dataclass
class ValidationResult:
    """Result of validating AI output against snapshot."""
    is_valid: bool = True
    violations: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    retry_count: int = 0
    fallback_used: bool = False
    validated_claim_ids: List[str] = field(default_factory=list)
    validated_source_ids: List[str] = field(default_factory=list)
    detected_contradictions: List[str] = field(default_factory=list)
    detected_hallucinations: List[str] = field(default_factory=list)


def validate_ai_output(
    ai_text: str,
    snapshot_dict: dict,
    max_retries: int = 1,
) -> ValidationResult:
    """Validate AI output against the EvidenceSnapshot.

    Args:
        ai_text: The text generated by the AI model
        snapshot_dict: The EvidenceSnapshot as a dict
        max_retries: Maximum number of retries before fallback

    Returns:
        ValidationResult with violations, warnings, and detected issues.
    """
    result = ValidationResult()

    if not ai_text or not ai_text.strip():
        result.is_valid = False
        result.violations.append("EMPTY_AI_OUTPUT")
        result.fallback_used = True
        return result

    # ── 1. Check for "nessun record nominativo" when origin_record is VERIFIED ──
    origin_state = snapshot_dict.get("origin_record", {}).get("state", "ABSENT")
    if origin_state == "VERIFIED":
        denial_patterns = [
            r"nessun\s+record\s+nominativo",
            r"nessun\s+record\s+diretto",
            r"nessun\s+dato\s+nominativo",
            r"non\s+è\s+stato\s+trovato\s+alcun\s+record",
            r"tutti\s+i\s+candidati\s+(sono\s+)?insufficienti",
            r"tutti\s+i\s+candidati\s+(sono\s+)?non\s+pertinenti",
            r"nessuna\s+fonte\s+nominativa",
        ]
        for pattern in denial_patterns:
            if re.search(pattern, ai_text, re.IGNORECASE):
                result.is_valid = False
                result.detected_contradictions.append(
                    f"AI denies origin record but snapshot has VERIFIED state: pattern={pattern}"
                )
                result.violations.append(
                    f"CONTRADICTS_ORIGIN_RECORD: AI says no record but origin_record.state=VERIFIED"
                )

    # ── 2. Check for "dati mancanti" that are actually present ──
    accepted_claims = snapshot_dict.get("accepted_claims", [])
    accepted_fields = {c.get("field_name"): c for c in accepted_claims}

    missing_patterns = [
        (r"matricola\s+(non\s+)?(trovata|presente|disponibile|nota)", "service_number"),
        (r"residenza\s+(non\s+)?(trovata|presente|disponibile|nota)", "residence"),
        (r"prigionia\s+(non\s+)?(trovata|presente|disponibile|nota)", "captivity"),
        (r"sepoltura\s+(non\s+)?(trovata|presente|disponibile|nota)", "burial"),
        (r"paternità\s+(non\s+)?(trovata|presente|disponibile|nota)", "paternity"),
        (r"data\s+(di\s+)?morte\s+(non\s+)?(trovata|presente|disponibile|nota)", "death_date"),
        (r"luogo\s+(di\s+)?morte\s+(non\s+)?(trovata|presente|disponibile|nota)", "death_place"),
    ]

    for pattern, field_name in missing_patterns:
        if field_name in accepted_fields:
            claim = accepted_fields[field_name]
            if claim.get("object_value"):
                if re.search(pattern, ai_text, re.IGNORECASE):
                    result.warnings.append(
                        f"AI says {field_name} missing but snapshot has value: {claim.get('object_value')}"
                    )

    # ── 3. Check for hallucinated URLs not in snapshot ──
    all_snapshot_urls = set()
    for s in snapshot_dict.get("accepted_origin_evidence_sources", []):
        all_snapshot_urls.add(s.get("canonical_url", ""))
    for s in snapshot_dict.get("accepted_independent_evidence_sources", []):
        all_snapshot_urls.add(s.get("canonical_url", ""))
    for s in snapshot_dict.get("consulted_sources", []):
        all_snapshot_urls.add(s.get("canonical_url", ""))
    for s in snapshot_dict.get("context_sources", []):
        all_snapshot_urls.add(s.get("canonical_url", ""))
    for s in snapshot_dict.get("research_leads", []):
        all_snapshot_urls.add(s.get("canonical_url", ""))

    # Find URLs in AI text
    ai_urls = set(re.findall(r'https?://[^\s<>"\)\]]+', ai_text))
    for url in ai_urls:
        # Normalize for comparison (remove trailing punctuation)
        clean_url = url.rstrip('.,;:!?)]')
        if clean_url not in all_snapshot_urls:
            # Check if it's a substring of any snapshot URL
            found = False
            for snap_url in all_snapshot_urls:
                if clean_url in snap_url or snap_url in clean_url:
                    found = True
                    break
            if not found:
                result.detected_hallucinations.append(f"UNAUTHORIZED_URL: {clean_url}")
                result.warnings.append(f"AI contains URL not in snapshot: {clean_url}")

    # ── 4. Check for hallucinated archive names ──
    # Look for "Archivio di Stato di {X}" patterns not in verified suggestions
    archive_pattern = r'Archivio\s+di\s+Stato\s+di\s+([A-Z][a-z]+(?:\s+[a-z]+)*)'
    found_archives = re.findall(archive_pattern, ai_text)
    verified_archives = set()
    # Extract from accepted sources
    for s in snapshot_dict.get("accepted_origin_evidence_sources", []):
        if "Archivio di Stato" in s.get("archive", ""):
            verified_archives.add(s.get("archive", ""))

    for arch_name in found_archives:
        full_name = f"Archivio di Stato di {arch_name}"
        if full_name not in verified_archives:
            result.detected_hallucinations.append(f"UNVERIFIED_ARCHIVE: {full_name}")
            result.warnings.append(f"AI mentions unverified archive: {full_name}")

    # ── 5. Check for name typos ──
    target_name = snapshot_dict.get("target_id", "")
    # Extract target name from accepted claims or origin record
    origin_record = snapshot_dict.get("origin_record", {})
    # Check for common typos in the target name
    # This is heuristic — check if AI text contains a close but wrong variant
    accepted_names = set()
    for c in accepted_claims:
        if c.get("field_name") in ("birth_place",):
            continue
        val = c.get("object_value", "")
        if val:
            accepted_names.add(val.upper())

    # Check for "FEDERIO" when target is "FEDERICO", etc.
    for name in accepted_names:
        if len(name) > 4:
            # Check for single-character substitutions
            for i in range(len(name)):
                typo_variant = name[:i] + ("X" if name[i] != "X" else "Y") + name[i+1:]
                if typo_variant in ai_text.upper() and typo_variant != name:
                    result.detected_hallucinations.append(
                        f"POSSIBLE_NAME_TYPO: found '{typo_variant}' expected '{name}'"
                    )

    # ── 6. Check for invented year arithmetic ──
    # Pattern: "classe 1885 → classe 1865?"
    arithmetic_pattern = r'(\d{4})\s*[→\-]+\s*(?:classe\s+)?(\d{4})\s*\?'
    arithmetic_matches = re.findall(arithmetic_pattern, ai_text)
    for m in arithmetic_matches:
        result.detected_hallucinations.append(
            f"INVENTED_YEAR_ARITHMETIC: {m[0]} → {m[1]}"
        )

    # ── 7. Determine if fallback is needed ──
    if result.detected_contradictions:
        result.is_valid = False
        result.violations.extend(result.detected_contradictions)

    if result.violations:
        if result.retry_count < max_retries:
            result.retry_count += 1
            # Caller should retry with violation feedback
        else:
            result.fallback_used = True

    return result


def generate_deterministic_report(snapshot_dict: dict) -> str:
    """Generate a deterministic report without AI.

    This is the fallback when AI output fails validation.
    It uses ONLY data from the snapshot, with no external generation.
    """
    resolution = snapshot_dict.get("resolution_state", "UNRESOLVED")
    origin = snapshot_dict.get("origin_record", {})
    origin_state = origin.get("state", "ABSENT")
    accepted_claims = snapshot_dict.get("accepted_claims", [])
    missing_claims = snapshot_dict.get("missing_claims", [])
    rejected = snapshot_dict.get("rejected_candidates", [])
    limitations = snapshot_dict.get("research_limitations", [])
    reconciliation = snapshot_dict.get("reconciliation", {})

    lines = []

    # Section 1: Identità ricercata
    target_id = snapshot_dict.get("target_id", "")
    lines.append("## 1. Identità ricercata")
    lines.append(f"Target ID: {target_id}")
    lines.append("")

    # Section 2: Cosa attesta la fonte d'origine
    lines.append("## 2. Cosa attesta la fonte d'origine")
    if origin_state == "VERIFIED":
        lines.append("Il nominativo è presente nel record dell'Albo d'Oro importato dalla piattaforma.")
        if accepted_claims:
            lines.append("Il record attribuisce al soggetto i seguenti dati:")
            for claim in accepted_claims:
                lines.append(f"  - **{claim.get('field_name', '')}**: {claim.get('object_value', '')}")
    elif origin_state == "PRESENT_UNVERIFIED_LINEAGE":
        lines.append(
            "La piattaforma contiene un record locale compatibile, ma il collegamento "
            "alla fonte d'origine non è ancora verificabile. Il dato resta una pista "
            "qualificata e non viene presentato come prova."
        )
    else:
        lines.append("Nessun record d'origine verificato disponibile.")
    lines.append("")

    # Section 3: Corroborazione esterna
    lines.append("## 3. Corroborazione esterna trovata o non trovata")
    independent_count = reconciliation.get("independent_evidence_sources", 0)
    if independent_count == 0:
        lines.append(
            "La ricerca esterna eseguita in questa sessione non ha prodotto una seconda "
            "fonte nominativa indipendente accettabile. Questo non smentisce il record "
            "d'origine e non dimostra l'assenza di altri documenti."
        )
    else:
        lines.append(f"Trovate {independent_count} fonti indipendenti di corroborazione.")
    lines.append("")

    # Section 4: Contraddizioni e omonimi esclusi
    lines.append("## 4. Contraddizioni e omonimi esclusi")
    if rejected:
        for r in rejected:
            lines.append(f"  - {r.get('name', '')}: {', '.join(r.get('reason_codes', []))}")
    else:
        lines.append("Nessun omonimo escluso.")
    lines.append("")

    # Section 5: Limiti tecnici
    lines.append("## 5. Limiti tecnici della sessione")
    if limitations:
        for lim in limitations:
            lines.append(f"  - {lim}")
    else:
        lines.append("Nessun limite tecnico segnalato.")
    lines.append("")

    # Section 6: Dati ancora mancanti
    lines.append("## 6. Dati ancora mancanti")
    if missing_claims:
        lines.append(f"Campi non coperti da claim accettati: {', '.join(missing_claims)}")
    else:
        lines.append("Nessun dato mancante.")
    lines.append("")

    # Section 7: Prossimi passi
    lines.append("## 7. Prossimi passi verificati e ordinati per priorità")
    lines.append("  1. Verificare la lineage del record d'origine (URL completo, base URL)")
    lines.append("  2. Consultare l'Archivio di Stato territorialmente competente per fogli matricolari")
    lines.append("  3. Verificare presso l'ICRC per eventuali schede di prigionia")
    lines.append("")

    # Section 8: Fonti
    lines.append("## 8. Fonti probative, fonti contestuali e piste separate")
    origin_sources = snapshot_dict.get("accepted_origin_evidence_sources", [])
    context_sources = snapshot_dict.get("context_sources", [])
    leads = snapshot_dict.get("research_leads", [])

    if origin_sources:
        lines.append("### Fonti probative (record d'origine)")
        for s in origin_sources:
            lines.append(f"  - {s.get('source_id', '')}: {s.get('provider', '')}")
    if context_sources:
        lines.append("### Fonti contestuali")
        for s in context_sources:
            lines.append(f"  - {s.get('source_id', '')}: {s.get('title', '')}")
    if leads:
        lines.append(f"### Piste non verificate ({len(leads)})")
    lines.append("")

    # Metadata
    lines.append("## Metadati tecnici")
    lines.append(f"  Snapshot: {snapshot_dict.get('snapshot_id', '')}")
    lines.append(f"  Hash: {snapshot_dict.get('snapshot_hash', '')}")
    lines.append(f"  Resolution: {resolution}")
    lines.append(f"  Origin state: {origin_state}")
    lines.append(f"  Provider: deterministic (no AI)")

    return "\n".join(lines)
