IMI_PDFS = {
    "A": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_174_Elenco_A.pdf",
    "B": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_203_Elenco_B.pdf",
    "C": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_204_Elenco_C.pdf",
    "D": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_234_Elenco_D.pdf",
    "E": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_204_Elenco_E.pdf",
    "F": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_210_Elenco_F.pdf",
    "G": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_210_Elenco_G.pdf",
    "I": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_217_Elenco_I.pdf",
    "L": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_217_Elenco_L.pdf",
    "M": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_216_Elenco_M.pdf",
    "N": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_204_Elenco_N.pdf",
    "O": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_204_Elenco_O.pdf",
    "P": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_204_Elenco_P.pdf",
    "Q": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_022_Elenco_Q.pdf",
    "R": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_022_Elenco_R.pdf",
    "S": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_022_Elenco_S.pdf",
    "T": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_022_Elenco_T.pdf",
    "U": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_022_Elenco_U.pdf",
    "V": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_022_Elenco_V.pdf",
    "Z": "https://archiviodistatobolzano.cultura.gov.it/fileadmin/risorse/PDF/IMI-CAR/IMI_OCR/Elenchi_OCR/ASBZ_CG_022_Elenco_Z.pdf",
}

COLUMNS = [
    "cognome",
    "nome",
    "data_nascita",
    "luogo_nascita",
    "residenza",
    "grado",
    "luogo_cattura",
    "data_cattura",
    "luogo_internamento",
    "matricola",
    "arbeitskommando",
    "mansione",
    "sorte",
    "data",
    "documenti",
]
