"""V7 Event Ontology & AggregateDefinitionRegistry.

This module defines:
  - EventOntology: canonical event types, phases, and relationships
  - AggregateDefinition: registered aggregate queries with deterministic definitions
  - AggregateDefinitionRegistry: versioned registry of aggregate definitions

Key principles:
  1. Aggregate queries are DETERMINISTIC — defined in a registry, not generated by AI
  2. Event types follow a canonical ontology (battle, offensive, retreat, armistice, etc.)
  3. Event phases are structured (preparation, execution, aftermath)
  4. The AI cannot invent aggregate definitions — it can only use registered ones
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Dict, List, Optional, Any, Tuple


# ─── Event ontology ─────────────────────────────────────────────────────────

EVENT_TYPES = [
    "battaglia",          # battle
    "offensiva",          # offensive
    "ritirata",           # retreat
    "avanzata",           # advance
    "assedio",            # siege
    "bombardamento",      # bombardment
    "armistizio",         # armistice
    "dichiarazione_guerra",  # war declaration
    "trattato_pace",      # peace treaty
    "internamento",       # internment
    "rimpatrio",          # repatriation
    "deportazione",       # deportation
    "liberazione",        # liberation
    "eccidio",            # massacre
    "altro",              # other
]

EVENT_PHASES = [
    "preparazione",       # preparation
    "esecuzione",         # execution
    "sviluppo",           # development
    "conclusione",        # conclusion
    "postumi",            # aftermath
]

EVENT_RELATIONS = [
    "sub_event_of",       # this event is part of a larger event
    "preceded_by",        # this event follows another
    "caused_by",          # this event was caused by another
    "resulted_in",        # this event resulted in another
    "concurrent_with",    # this event happened at the same time
    "same_as",            # this event is the same as another (alias)
]


@dataclass
class CanonicalEvent:
    """A canonical event in the V7 ontology."""
    event_id: str = ""
    name: str = ""
    event_type: str = ""
    conflict: str = "UNKNOWN"  # WWI|WWII|CONFLICTING
    start_date: str = ""
    end_date: str = ""
    location: str = ""
    description: str = ""
    parent_event_id: str = ""
    phases: List[Dict[str, Any]] = field(default_factory=list)
    aliases: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if not self.event_id:
            raw = json.dumps({
                "name": self.name,
                "type": self.event_type,
                "start": self.start_date,
                "end": self.end_date,
            }, sort_keys=True, ensure_ascii=False)
            self.event_id = f"evt_{hashlib.sha256(raw.encode()).hexdigest()[:16]}"

    def to_dict(self) -> dict:
        return asdict(self)


class EventOntology:
    """Canonical event ontology for V7.

    Provides:
      - Event type classification
      - Phase structuring
      - Relationship validation
      - Alias resolution
    """

    def __init__(self):
        self._events: Dict[str, CanonicalEvent] = {}
        self._aliases: Dict[str, str] = {}  # alias -> event_id

    def register_event(self, event: CanonicalEvent):
        self._events[event.event_id] = event
        for alias in event.aliases:
            self._aliases[alias.lower()] = event.event_id

    def get_event(self, event_id: str) -> Optional[CanonicalEvent]:
        return self._events.get(event_id)

    def resolve_alias(self, name: str) -> Optional[str]:
        """Resolve an event name or alias to its canonical event_id."""
        return self._aliases.get(name.lower())

    def classify_type(self, name: str, description: str = "") -> str:
        """Classify an event name into a canonical event type."""
        name_lower = name.lower()
        desc_lower = description.lower()

        type_keywords = {
            "battaglia": ["battaglia", "battle", "combat"],
            "offensiva": ["offensiva", "offensive", "push", "assalto"],
            "ritirata": ["ritirata", "retreat", "ripiegamento"],
            "avanzata": ["avanzata", "advance", "progresso"],
            "assedio": ["assedio", "siege", "accerchiamento"],
            "bombardamento": ["bombardamento", "bombing", "bombard"],
            "armistizio": ["armistizio", "armistice"],
            "dichiarazione_guerra": ["dichiarazione", "declaration"],
            "trattato_pace": ["trattato", "treaty", "pace", "peace"],
            "internamento": ["internamento", "internment", "prigionia"],
            "rimpatrio": ["rimpatrio", "repatriation", "ritorno"],
            "deportazione": ["deportazione", "deportation"],
            "liberazione": ["liberazione", "liberation"],
            "eccidio": ["eccidio", "massacre", "strage"],
        }

        for evt_type, keywords in type_keywords.items():
            for kw in keywords:
                if kw in name_lower or kw in desc_lower:
                    return evt_type

        return "altro"

    def all_events(self) -> Dict[str, CanonicalEvent]:
        return dict(self._events)


# ─── Aggregate definition registry ──────────────────────────────────────────

@dataclass
class AggregateDefinition:
    """A registered aggregate query definition.

    Aggregate queries are DETERMINISTIC — they are defined in the registry
    and cannot be invented by the AI. The AI can only reference registered
    definitions by their ID.
    """
    definition_id: str = ""
    name: str = ""
    description: str = ""
    query_template: str = ""  # SQL or structured query template
    parameters: List[Dict[str, Any]] = field(default_factory=list)
    output_schema: Dict[str, Any] = field(default_factory=dict)
    version: str = "1.0"
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def __post_init__(self):
        if not self.definition_id:
            raw = json.dumps({
                "name": self.name,
                "template": self.query_template,
                "version": self.version,
            }, sort_keys=True, ensure_ascii=False)
            self.definition_id = f"agg_{hashlib.sha256(raw.encode()).hexdigest()[:16]}"

    def to_dict(self) -> dict:
        return asdict(self)


class AggregateDefinitionRegistry:
    """Versioned registry of aggregate query definitions.

    The AI cannot invent aggregate queries — it can only reference
    registered definitions by their definition_id.
    """

    def __init__(self):
        self._definitions: Dict[str, AggregateDefinition] = {}
        self._register_defaults()

    def _register_defaults(self):
        """Register default aggregate definitions."""
        defaults = [
            AggregateDefinition(
                name="count_internati_by_year",
                description="Count of IMI internees grouped by birth year",
                query_template="SELECT anno_nascita, COUNT(*) as count FROM internati GROUP BY anno_nascita ORDER BY count DESC",
                parameters=[],
                output_schema={"anno_nascita": "str", "count": "int"},
            ),
            AggregateDefinition(
                name="count_caduti_by_luogo",
                description="Count of fallen soldiers grouped by death place",
                query_template="SELECT luogo_morte, COUNT(*) as count FROM caduti_albooro WHERE luogo_morte IS NOT NULL AND luogo_morte != '' GROUP BY luogo_morte ORDER BY count DESC LIMIT 50",
                parameters=[],
                output_schema={"luogo_morte": "str", "count": "int"},
            ),
            AggregateDefinition(
                name="count_decorati_by_type",
                description="Count of decorated soldiers grouped by decoration type",
                query_template="SELECT decorazione, COUNT(*) as count FROM decorati_nastroazzurro GROUP BY decorazione ORDER BY count DESC",
                parameters=[],
                output_schema={"decorazione": "str", "count": "int"},
            ),
            AggregateDefinition(
                name="count_internati_by_campo",
                description="Count of IMI internees grouped by internment camp",
                query_template="SELECT luogo_internamento, COUNT(*) as count FROM internati WHERE luogo_internamento IS NOT NULL AND luogo_internamento != '' GROUP BY luogo_internamento ORDER BY count DESC LIMIT 50",
                parameters=[],
                output_schema={"luogo_internamento": "str", "count": "int"},
            ),
            AggregateDefinition(
                name="count_events_by_conflict",
                description="Count of events grouped by conflict type",
                query_template="SELECT conflitto, COUNT(*) as count FROM eventi_1gm GROUP BY conflitto ORDER BY count DESC",
                parameters=[],
                output_schema={"conflitto": "str", "count": "int"},
            ),
            AggregateDefinition(
                name="temporal_distribution_caduti",
                description="Temporal distribution of fallen soldiers by year of death",
                query_template="SELECT anno_morte, COUNT(*) as count FROM caduti_albooro WHERE anno_morte IS NOT NULL AND anno_morte != '' GROUP BY anno_morte ORDER BY anno_morte",
                parameters=[],
                output_schema={"anno_morte": "str", "count": "int"},
            ),
            AggregateDefinition(
                name="geographic_distribution_internati",
                description="Geographic distribution of IMI internees by birth place",
                query_template="SELECT luogo_nascita, COUNT(*) as count FROM internati WHERE luogo_nascita IS NOT NULL AND luogo_nascita != '' GROUP BY luogo_nascita ORDER BY count DESC LIMIT 100",
                parameters=[],
                output_schema={"luogo_nascita": "str", "count": "int"},
            ),
        ]

        for d in defaults:
            self._definitions[d.definition_id] = d

    def register(self, definition: AggregateDefinition):
        self._definitions[definition.definition_id] = definition

    def get(self, definition_id: str) -> Optional[AggregateDefinition]:
        return self._definitions.get(definition_id)

    def get_by_name(self, name: str) -> Optional[AggregateDefinition]:
        for d in self._definitions.values():
            if d.name == name:
                return d
        return None

    def all_definitions(self) -> Dict[str, AggregateDefinition]:
        return dict(self._definitions)

    def list_definition_ids(self) -> List[str]:
        return list(self._definitions.keys())

    def execute(self, definition_id: str, db_conn=None) -> Optional[Dict[str, Any]]:
        """Execute an aggregate query definition.

        Returns the aggregate result dict, or None if the definition doesn't exist.
        """
        definition = self.get(definition_id)
        if not definition:
            return None

        if not db_conn:
            from database import get_conn
            db_conn = get_conn()

        try:
            rows = db_conn.execute(definition.query_template).fetchall()
            results = [dict(r) for r in rows]
            return {
                "definition_id": definition_id,
                "name": definition.name,
                "description": definition.description,
                "results": results,
                "row_count": len(results),
            }
        except Exception as e:
            return {
                "definition_id": definition_id,
                "name": definition.name,
                "error": str(e),
                "results": [],
                "row_count": 0,
            }
        finally:
            if db_conn:
                db_conn.close()
